sudo: required
language: generic

services:
  - docker

script:
  - docker run -it --rm -v "$(pwd):/opt/build" -w /opt/build mozilla/sbt sbt compile
  - docker run -it --rm -v "$(pwd):/opt/build" -w /opt/build mozilla/sbt sbt test
